### ISSUE TITLE
Where should I change when the platform is different

### ISSUE THREAD

**Issue by zyt1024** [salehjg/DeepPoint-V2-FPGA#1]
hello,I try to use U200 to test the code, where should I modify

**Comment by salehjg** [comment]
Hi there,
Sorry for my late reponse.

You can try various platforms by setting [DSA_NAME ](https://github.com/salehjg/DeepPoint-V2-FPGA/blob/45413a30c52ac3a1ed671c98fbe0dd2f2e8bb005/CMakeLists.txt#L11) to the  `*.xpfm` file's absolute path.

Also, you might want to comment out lines 2,3, and 4 in the same file linked above.

**Comment by zyt1024** [comment]
Thank you!
