### ISSUE TITLE
Compiling FPGA Kernels Errors

### ISSUE THREAD

**Issue by TG-MIO** [salehjg/DeepPoint-V2-FPGA#4]
Dear author, hello.
I encountered an error while doing the make compile_swemu step.
The error message is as follows:

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build/4
ERROR: [XOCC 60-623] Unsupported input file type specified.

Every module reports this error.Do you have any idea how to solve this problem?
Wish you a happy life!

**Comment by salehjg** [comment]
Hi TG-MIO,

The version of SDx that the project is based upon, does not support the
simulation of multi-PE kernels in SW-EMU mode.
For kernel verification on CPU, use the unit tests located at
`test/kerneltests`. They support multi PE simulation but they do not
include the host program in the simulation. That is not a problem, since we
also have OclTests just for that purpose.

In short, do not use SW-EMU.

Please let me know if you have any questions.

Happy coding.

**Comment by TG-MIO** [comment]
@salehjg 
Thank you for your answer！I successfully ran kernel verification according to what you said.
But when I went to compile_hw, I still encountered the error I mentioned above, reporting it exactly the same.
Do you have any idea how to solve this problem?

**Comment by salehjg** [comment]
I see.

Could you please share these details:

- the version of SDx
- the exact commands to replicate the problem.
- CMake version
- your OS

This way hopefully I can help you better.

**Comment by TG-MIO** [comment]
@salehjg 
sure!
My environment is Ubuntu 18.04/SDAccel 2019.1/CMake 3.10.
I ran it on a virtual machine.


I encountered errors when typing the command "make compile_hw" in the "DeepPoint-V2-FPGA/build" directory.

The error message is as follows:
ERROR: [XOCC 60-602] Source file does not exist: /home/icwork/DeepPoint-V2-FPGA/build/4
ERROR: [XOCC 60-623] Unsupported input file type specified.

These error messages are logged in multiple log files,such as xocc_concat_hw.log,xocc_datamover_hw.log,xocc_gather_hw.log...etc.

I'm wondering if this is caused by my XRT being wrong or my.xpfm file being incompatible?
Thank you for your warm help!

**Comment by salehjg** [comment]
I am not sure what that `4` is at the end of the first error msg. It seems like the input arguments to XOCC are wrong. Are you sure you don't have more than one version of SDx installed on your system? Or can you upgrade your CMake if it is not that complicated?

Could you please follow this and upload the log files here?
```
cd DeepPoint-V2-FPGA
mkdir build-try01
cd build-try01
cmake ..
bash autobuild_hw
```

Then please provide `autobuild_hw_log.txt` here or any other log file relating to Cmake so maybe we can figure out the issue together.

**Comment by TG-MIO** [comment]
@salehjg 
yes，I installed vitis 2019.2 earlier.
According to what you said, I upgraded cmake to 3.21 and then I did what you said.
Here is the information for the log file:
`================================================================================
================================================================================
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
CMakeFiles/compile_hw.dir/build.make:70: recipe for target 'CMakeFiles/compile_hw' failed
CMakeFiles/Makefile2:582: recipe for target 'CMakeFiles/compile_hw.dir/all' failed
CMakeFiles/Makefile2:589: recipe for target 'CMakeFiles/compile_hw.dir/rule' failed
Makefile:231: recipe for target 'compile_hw' failed
================================================================================
================================================================================
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/vivado_prop:run.impl_1.{STEPS.ROUTE_DESIGN.TCL.PRE}={/home/ic/Desktop/work/DeepPoint-V2-FPGA/build-try01/PreRoute.tcl}
ERROR: [XOCC 60-623] Unsupported input file type specified.
CMakeFiles/link_hw.dir/build.make:70: recipe for target 'CMakeFiles/link_hw' failed
CMakeFiles/Makefile2:608: recipe for target 'CMakeFiles/link_hw.dir/all' failed
CMakeFiles/Makefile2:615: recipe for target 'CMakeFiles/link_hw.dir/rule' failed
Makefile:244: recipe for target 'link_hw' failed
================================================================================
================================================================================
Total Elapsed Seconds: 25
Total Elapsed Hours: .006`

Thank you for your efforts to help, I wish you a happy life and smooth work.

**Comment by TG-MIO** [comment]
@salehjg 
Yes!
I had vitis2019.2 installed on my system before.
As you said, I upgraded cmake to version 3.21.
Then I carried out the operation according to your method, and the information in the log file is as follows:
```
================================================================================
================================================================================
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/4
ERROR: [XOCC 60-623] Unsupported input file type specified.
CMakeFiles/compile_hw.dir/build.make:70: recipe for target 'CMakeFiles/compile_hw' failed
CMakeFiles/Makefile2:582: recipe for target 'CMakeFiles/compile_hw.dir/all' failed
CMakeFiles/Makefile2:589: recipe for target 'CMakeFiles/compile_hw.dir/rule' failed
Makefile:231: recipe for target 'compile_hw' failed
================================================================================
================================================================================
Option Map File Used: '/home/ic/software/Xilinx/SDx/2019.1/data/sdx/xocc/optMap.xml'

****** xocc v2019.1 (64-bit)
  **** SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

ERROR: [XOCC 60-602] Source file does not exist: /home/ic/work/DeepPoint-V2-FPGA/build-try01/vivado_prop:run.impl_1.{STEPS.ROUTE_DESIGN.TCL.PRE}={/home/ic/Desktop/work/DeepPoint-V2-FPGA/build-try01/PreRoute.tcl}
ERROR: [XOCC 60-623] Unsupported input file type specified.
CMakeFiles/link_hw.dir/build.make:70: recipe for target 'CMakeFiles/link_hw' failed
CMakeFiles/Makefile2:608: recipe for target 'CMakeFiles/link_hw.dir/all' failed
CMakeFiles/Makefile2:615: recipe for target 'CMakeFiles/link_hw.dir/rule' failed
Makefile:244: recipe for target 'link_hw' failed
================================================================================
================================================================================
Total Elapsed Seconds: 25
Total Elapsed Hours: .006
```

Thank you for your answer, I wish you a smooth life and work!

**Comment by salehjg** [comment]
Thank you,
Unfortunately, these logs do not indicate the real problem.
Could you please run these and post **the output of your terminal** here?
```
cd DeepPoint-V2-FPGA
mkdir build-try02
cd build-try02
cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..
make compile_hw
make link_hw
```

I want to see the final generated XOCC commands for compilation and linkage procedures.

**Comment by TG-MIO** [comment]
@salehjg 
Thank you for your reply!
Unfortunately, I have some urgent matters these two days, I will follow your suggestion and reply to you as soon as possible after busy!

**Comment by TG-MIO** [comment]
@salehjg 
Hello!
I have solved the previous error of `make compile_hw`. The reason is that the version of XRT does not match and the Vivado HLS export IP is missing components.
`make compile_hw` passed after I replaced the XRT version and downloaded a patch for Vivado HLS from the AMD website.

I will continue with the next steps, thank you for your help!

**Comment by salehjg** [comment]
Nice to hear that the issue's resolved.
So, I am going to close this issue for now.
Please feel free to reopen it or post another one as you wish.
I would be happy to help!
