### ISSUE TITLE
There's a question about floating point arithmetic

### ISSUE THREAD

**Issue by TG-MIO** [salehjg/DeepPoint-V2-FPGA#6]
Hello! I have a question as to why in your paper, DGCNN is not quantified as int8 or int16, but as floating point arithmetic on FPGA. Is there any special consideration for this? In general, wouldn't quantifying the model and deploying it save hardware resources? Eager to get your answer, thank you!

**Comment by salehjg** [comment]
Good point.

We chose to perform arithmetic in Float32 to:

- keep the model as close as possible to the original one.

- given that the kernels were kept isolated from one another for
reusability (for example no fused kernels), it made sense to also stay on
float32.

**Comment by salehjg** [comment]
Please feel free to post another issue or reopen this one. I am closing this one for now.
